apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  serviceName: "flask-service"
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: danielrivni/my-flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
