apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: ${DOCKER_IMAGE}:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
